(() => {
 const uuid=()=>typeof crypto.randomUUID==='function'?crypto.randomUUID():'10000000-1000-4000-8000-100000000000'.replace(/[018]/g,c=>(Number(c)^crypto.getRandomValues(new Uint8Array(1))[0]&15>>Number(c)/4).toString(16));
 const endpoint='https://long-geology-portfolio.kagi5197.chatgpt.site/api/feedback';
 const dialog=document.createElement('dialog'); dialog.className='feedback-dialog';dialog.setAttribute('aria-labelledby','feedback-heading');
 dialog.innerHTML=`<button type="button" class="feedback-close" aria-label="Đóng hộp nhận xét">×</button><p class="eyebrow">FEEDBACK</p><h2 id="feedback-heading">Gửi nhận xét</h2><p class="feedback-title"></p><form><label>Họ tên<input name="name" autocomplete="name" placeholder="Tên người nhận xét" required maxlength="100"></label><label>Vai trò<select name="role"><option value="Giảng viên">Giảng viên</option><option value="Sinh viên">Sinh viên</option><option value="Khác">Khác</option></select></label><label>Nhận xét<textarea name="message" placeholder="Nhận xét về bài làm…" required minlength="3" maxlength="3000" rows="5"></textarea></label><label class="feedback-trap" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><p class="feedback-privacy">Nhận xét được gửi riêng cho chủ website, không hiển thị công khai. Không cần đăng nhập.</p><button class="button feedback-submit" type="submit">Gửi nhận xét</button><p class="feedback-status" role="status" aria-live="polite"></p></form>`;
 document.body.append(dialog);const form=dialog.querySelector('form'),status=dialog.querySelector('.feedback-status'),submit=dialog.querySelector('.feedback-submit');let assignmentId='',requestId='',sending=false,lastTrigger=null;
 const drafts=new Map();
 function close(){if(sending)return;drafts.set(assignmentId,{name:form.elements.name.value,role:form.elements.role.value,message:form.elements.message.value,id:requestId});dialog.close();lastTrigger?.focus();}
 dialog.querySelector('.feedback-close').addEventListener('click',close);
 dialog.addEventListener('cancel',e=>{e.preventDefault();close()});
 document.addEventListener('click',e=>{const trigger=e.target.closest('.feedback-open');if(!trigger)return;lastTrigger=trigger;assignmentId=trigger.dataset.assignmentId;dialog.querySelector('.feedback-title').textContent=trigger.dataset.assignmentTitle;form.reset();status.textContent='';submit.disabled=false;submit.textContent='Gửi nhận xét';const draft=drafts.get(assignmentId);requestId=draft?.id||uuid();if(draft){form.elements.name.value=draft.name;form.elements.role.value=draft.role;form.elements.message.value=draft.message;}dialog.showModal();form.elements.name.focus();});
 form.addEventListener('submit',async e=>{e.preventDefault();if(sending)return;sending=true;submit.disabled=true;submit.textContent='Đang gửi…';status.textContent='';try{const response=await fetch(endpoint,{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:requestId,assignmentId,name:form.elements.name.value,role:form.elements.role.value,message:form.elements.message.value,website:form.elements.website.value}),signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Chưa gửi được nhận xét.');status.textContent='Đã gửi nhận xét. Cảm ơn bạn đã góp ý!';status.classList.remove('is-error');form.reset();drafts.delete(assignmentId);requestId=uuid();submit.textContent='Đã gửi nhận xét';}catch(error){status.textContent=error.name==='TimeoutError'?'Kết nối chậm. Nội dung vẫn còn; bạn có thể thử gửi lại.':error.message;status.classList.add('is-error');submit.disabled=false;submit.textContent='Thử gửi lại';}finally{sending=false;}});
})();
